spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 20185584
    url: jdbc:mysql://localhost:3306/sipc115?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8082
  servlet:
    context-path: /
