spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 20185584
    url: jdbc:mysql://localhost:3306/sipc115?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  port: 8082
  servlet:
    context-path: /
