server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 20185584
    url: jdbc:mysql://localhost:3306/sipc115?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai

logging:
  file:
    name: logback-spring.xml