spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20185584
    url: jdbc:mysql://localhost:3306/sipc115?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

  redis:
    host: localhost
    port: 6379

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

server:
  port: 8082
  servlet:
    context-path: /

